from .robot_config import Config
import math

class TorqueController:
    def __init__(self):
        self.config = Config

    def compute_torques(self, current_states, target_angles, target_velocities):
        """
        Computes the target torques for all joints based on PID and Modification Modules.
        
        Args:
            current_states: list of ServoState objects
            target_angles: list of target positions (radians)
            target_velocities: list of target velocities (rad/s)
            
        Returns:
            list of computed torques (Nm or raw current value depending on servo)
        """
        output_torques = []
        
        for i in range(self.config.NUM_JOINTS):
            state = current_states[i]
            target_pos = target_angles[i]
            target_vel = target_velocities[i]
            
            # 1. Base PID Calculation
            # tau_d = P(goal_pos - curr_pos) - D(curr_vel) + P_v(goal_vel - curr_vel)
            # Simplification based on standard PD position + P velocity control
            pos_error = target_pos - state.position
            vel_error = target_vel - state.velocity
            
            base_torque = (self.config.P_POS * pos_error) \
                        - (self.config.D_POS * state.velocity) \
                        + (self.config.P_VEL * vel_error)
                        
            # 2. Shape Modification Module (For narrow spaces)
            # Restrains torques generated by large position deviations to prevent pushing against walls
            mu = self._calculate_shape_modification_factor(pos_error)
            modified_torque = base_torque * mu
            
            # 3. Curve Radius Modification Module (For unstructured pipes)
            # Detects load spikes (collision) and dynamically adjusts torque
            modified_torque = self._apply_radius_modification(modified_torque, state.load)
            
            # 4. Safety Limits
            final_torque = max(-self.config.MAX_TORQUE_NM, min(self.config.MAX_TORQUE_NM, modified_torque))
            
            output_torques.append(final_torque)
            
        return output_torques

    def _calculate_shape_modification_factor(self, pos_error):
        """
        Calculates the mu scaling parameter based on position deviation.
        If the error is small, mu is close to 1 (stiff).
        If the error is large (hit a wall), mu decreases (compliant).
        """
        abs_err = abs(pos_error)
        if abs_err < self.config.POS_ERROR_THRESHOLD:
            return self.config.MU_MAX
        else:
            # Exponential decay or linear decay for compliance
            # simple linear decay for prototype:
            factor = self.config.MU_MAX - (abs_err - self.config.POS_ERROR_THRESHOLD) * 0.5
            return max(self.config.MU_MIN, factor)

    def _apply_radius_modification(self, base_torque, current_load):
        """
        Modifies input torque based on radius deviation (detected via load spikes).
        tau_input_mod = tau_input - k * e_r
        We use current_load as a proxy for e_r (radius error) when it spikes against a pipe.
        """
        # If the load is very high opposing the movement, reduce the torque applied in that direction
        # Simple proxy implementation:
        if abs(current_load) > (self.config.MAX_TORQUE_NM * 0.8):
            # We are near stall. Reduce torque command to be compliant
            return base_torque * 0.5 
            
        return base_torque
